### ISSUE TITLE
Allow injection of redis client

### ISSUE THREAD

**Issue by elyobo** [mediocre/petty-cache#9]
I'd like to use this to talk to clustered redis, but the current implementation requires the use of the `redis` package which doesn't yet have redis cluster support.  If there was some way to change the way that the client rather than hard coding the use of the redis client it would allow the use of other libraries which do have that support.

**Comment by freshlogic** [comment]
Thanks to @crazyrohila this was implemented. I merged it today and it's out on NPM as v2.6.0.
